import = [
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[window]
opacity = 0.9
dimensions = {columns = 108, lines = 40}

[font]
normal = {family = "CaskaydiaCove Nerd Font Mono", style ="Regular"}
bold = {family = "CaskaydiaCove Nerd", style = "SemiBold"}
italic = {family = "CaskaydiaCove Nerd Font Mono", style ="Italic"}
bold_italic = {family = "CaskaydiaCove Nerd Font Mono", style = "SemiBoldItalic"}


